[package]
name = "wist-control"
version = "0.1.2" #@gxl:set(version)
edition = "2024"
license = "Apache-2.0"
rust-version = "1.85"

[dependencies]
jumo-derive = "0.1"
serde = { version = "1", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
wist-shared =  "0.1"

[lib]
path = "src/lib.rs"
